services:
  media-uploader:
    build: ./media-uploader
    ports:
      - "3001:3001"
    volumes:
      - ./media-uploader:/app
      - /app/node_modules
    command: npm run dev
    depends_on:
      - mongo
    networks:
      - opentel

  media-convert:
    build: ./media-convert
    ports:
      - "3002:3002"
    command: npm run dev
    volumes:
      - ./media-convert:/app
      - /app/node_modules
    networks:
      - opentel

  mongo:
    image: mongo:4.4.6
    ports:
      - "27017:27017"
    networks:
      - opentel
    volumes:
      - mongo_data:/data/db

networks:
  opentel:
    driver: bridge

volumes:
  mongo_data:
