services:
  media-uploader:
    build: ./media-uploader
    ports:
      - "3001:3001"
    volumes:
      - ./media-uploader:/app
      - /app/node_modules
    command: npm run dev
    depends_on:
      - mongo
    networks:
      - opentel

  media-convert:
    build: ./media-convert
    ports:
      - "3002:3002"
    command: npm run dev
    volumes:
      - ./media-convert:/app
      - /app/node_modules
    networks:
      - opentel

  mongo:
    image: mongo:4.4.6
    ports:
      - "27017:27017"
    networks:
      - opentel
    volumes:
      - mongo_data:/data/db

  jaeger:
    image: jaegertracing/all-in-one:latest
    environment:
      - COLLECTOR_ZIPKIN_HOST_PORT=9411 # To enable Zipkin endpoint (optional)
    ports:
      - "4317:4317"
      - "4318:4318"
      - "16686:16686" # Jaeger UI
      - "9411:9411" # Zipkin-compatible endpoint
    networks:
      - opentel

networks:
  opentel:
    driver: bridge

volumes:
  mongo_data:
